[build]
  command = ""
  publish = "."
[build.environment]
  # Signing key voor Mollie webhook signature verificatie
  MOLLIE_SIGNING_KEY = ""

[functions]
  node_bundler = "esbuild"

[functions."payment-webhook"]
  external_node_modules = ["twilio"]
